version: '2'
services:
    examenjhipster2-app:
        image: examenjhipster2
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://examenjhipster2-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=examenjhipster2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    examenjhipster2-mongodb:
        extends:
            file: mongodb.yml
            service: examenjhipster2-mongodb
