version: '2'
services:
    examenjhipster2-mongodb:
        image: mongo:4.0.2
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/examenjhipster2/mongodb/:/data/db/
